import React, { useContext } from 'react';
import { Deck, Notes, Slide, SlideContext } from 'spectacle';
import { useTheme } from './hooks/useTheme.js';
import { useLocale } from './hooks/useLocale.js';
import { PresentationChrome } from './components/PresentationChrome.jsx';
import { MainTalkSourceFooter } from './components/MainTalkSourceFooter.jsx';
import StepBridge from './components/StepBridge.jsx';
import { MAIN_TALK_EVIDENCE as E } from './data/mainTalkEvidence.mjs';
import { JapanGridMap } from './components/JapanGridMap.jsx';
import { JapanVPPMap } from './components/JapanVPPMap.jsx';
import { TokyoDuckCurveCaseStudy } from './components/TokyoDuckCurveCaseStudy.jsx';
import { TokyoFrequencyResponseCaseStudy } from './components/TokyoFrequencyResponseCaseStudy.jsx';
import VPPArchitecture from '../../presentation/src/components/VPPArchitecture.jsx';
import ChoreographyLoop from '../../presentation/src/components/ChoreographyLoop.jsx';
import ResponseTimeline from '../../presentation/src/components/ResponseTimeline.jsx';
import AggregationPyramid from '../../presentation/src/components/AggregationPyramid.jsx';

const coreSlides = 21;
const page = { padding: '38px 58px', backgroundColor: 'var(--color-washi-paper)' };
const darkPage = { padding: '38px 58px', backgroundColor: 'var(--color-bg)' };
function Lazy({ children }) { const c = useContext(SlideContext); return c?.isSlideActive ? children : null; }
const Title = ({ children, tone = 'var(--color-washi-ink)' }) => <h1 style={{ margin: 0, color: tone, fontFamily: 'var(--font-heading)', fontSize: 48, lineHeight: 1.08 }}>{children}</h1>;
const Body = ({ children, tone = 'var(--color-washi-ink)' }) => <p style={{ maxWidth: 900, color: tone, fontFamily: 'var(--font-body)', fontSize: 24, lineHeight: 1.42 }}>{children}</p>;
const Source = ({ evidence, caseNote }) => <MainTalkSourceFooter evidence={evidence} caseNote={caseNote} detailUrl="whatisavpp.com/research/japan-energy-flexibility" />;
function template({ slideNumber }) { return <div style={{ position: 'absolute', right: 22, bottom: 15, fontFamily: 'var(--font-mono)', color: 'var(--color-dim)', fontSize: 12 }}>{Math.min(slideNumber, coreSlides)} / {coreSlides}</div>; }

export default function MainTalk() {
  const { theme, cycleTheme, spectacleTheme } = useTheme();
  const { locale, setLocale } = useLocale();
  return <><PresentationChrome theme={theme} cycleTheme={cycleTheme} locale={locale} setLocale={setLocale} /><Deck theme={spectacleTheme} template={template}>
    <Slide padding="0"><div style={{ height: '100%', position: 'relative', background: 'var(--color-washi-paper)' }}><Lazy><JapanGridMap variant="washi" height={580} /></Lazy><div style={{ position: 'absolute', top: 28, left: 38, maxWidth: 620, padding: '20px 24px', background: 'color-mix(in srgb, var(--color-washi-paper) 88%, transparent)' }}><Title>Japan cannot borrow</Title><Body>An island system must solve each imbalance at home.</Body></div></div><Notes>Orientation: island system; low primary-energy self-sufficiency; little room when supply tightens.</Notes></Slide>
    <Slide {...page}><div style={{ fontFamily: 'var(--font-mono)', color: 'var(--color-washi-alert)', letterSpacing: '0.16em' }}>ONE QUESTION</div><Title>What happens at the 50 / 60 Hz seam?</Title><Body>When the grid is split in two, flexibility has to be coordinated where the imbalance appears.</Body><div style={{ marginTop: 48, height: 12, maxWidth: 820, background: 'linear-gradient(90deg, var(--color-primary) 0 48%, var(--color-washi-alert) 48% 52%, var(--color-washi-solar) 52%)' }} /></Slide>
    <Slide {...page}><div style={{ fontFamily: 'var(--font-mono)', color: 'var(--color-washi-alert)', letterSpacing: '0.16em' }}>EXPOSURE</div><div style={{ marginTop: 78, fontFamily: 'var(--font-heading)', color: 'var(--color-washi-ink)', fontSize: 112, lineHeight: 0.9 }}>15.3%</div><Title>primary-energy self-sufficiency</Title><Body>That is why timing, control, and trusted local capacity matter.</Body><Source evidence={E.japanEnergy} /></Slide>

    <Slide {...page}><Title tone="var(--color-washi-alert)">A real noon operating constraint</Title><div style={{ marginTop: 48, padding: '28px 32px', borderLeft: '8px solid var(--color-washi-alert)', background: 'color-mix(in srgb, var(--color-washi-alert) 7%, transparent)' }}><div style={{ fontFamily: 'var(--font-mono)', color: 'var(--color-washi-alert)', fontSize: 20, letterSpacing: '0.12em' }}>4 MAY 2025 · 12:00–12:30</div><div style={{ marginTop: 18, fontFamily: 'var(--font-heading)', fontSize: 48, lineHeight: 1.08 }}>Kyushu T&amp;D recorded up to 5.09 GW of renewable-output control.</div></div><Body>This is a maximum power value, not an energy total: a single interval when local clean generation had to be constrained.</Body><Source evidence={E.kyushuControl} /></Slide>
    <Slide padding="0"><StepBridge count={3}>{step => <TokyoDuckCurveCaseStudy step={step} />}</StepBridge><Notes>Tokyo-area reported case. Noon: curtailment context; then illustrative household charging; then illustrative dusk support. Do not claim fleet capacity or delivered grid impact.</Notes></Slide>
    <Slide {...page}><Title>Store it for later</Title><Body>Batteries store noon generation. EVs and heat pumps shift consumption into the solar window. The evening ramp becomes smaller and easier to serve.</Body></Slide>
    <Slide {...page}><Title>A Japanese platform for that flexibility</Title><Body>Shizen Connect’s public materials describe a VPP platform for coordinating distributed energy resources.</Body><Source evidence={E.shizenConnect} caseNote={{ title: 'Shizen Connect', scope: 'Platform context for distributed energy resources', qualifier: 'Company-reported platform scope · not a performance result' }} /></Slide>

    <Slide {...page}><div style={{ fontFamily: 'var(--font-mono)', color: 'var(--color-primary)', letterSpacing: '0.16em' }}>PROOF 2 · FAILURE RESPONSE</div><Title>Respond when the system is tight</Title><Body>Tokyo’s March 2022 cold-snap emergency shows the operational problem: capacity, demand, and trusted flexibility must move together.</Body><Notes>Use the documented 2022 supply-demand event; do not call it a frequency incident.</Notes></Slide>
    <Slide padding="0"><StepBridge count={3}>{step => <TokyoFrequencyResponseCaseStudy mode="incident" step={step} />}</StepBridge><Notes>Tokyo, March 2022: earthquake-related generation loss, a cold snap, then the 22 March supply-demand warning. The final flexibility overlay is illustrative, not a reported VPP dispatch.</Notes></Slide>
    <Slide padding="0"><Lazy><TokyoFrequencyResponseCaseStudy mode="graph" /></Lazy><Notes>Recovery state becomes a graph: telemetry up, dispatch intent down, acknowledgement back.</Notes></Slide>
    <Slide {...darkPage}><Title tone="var(--color-heading)">The VPP is the control plane</Title><div style={{ display: 'grid', gridTemplateColumns: '1.1fr .9fr', gridTemplateRows: '250px 190px', gap: 14, marginTop: 16 }}><div style={{ gridRow: 'span 2' }}><Lazy><VPPArchitecture /></Lazy></div><div><Lazy><ChoreographyLoop /></Lazy></div><div><Lazy><ResponseTimeline /></Lazy></div></div></Slide>

    <Slide {...page}><div style={{ fontFamily: 'var(--font-mono)', color: 'var(--color-secondary)', letterSpacing: '0.16em' }}>PROOF 3 · DAILY OPERATION</div><Title>Use demand smarter</Title><Body>The same control plane can shift ordinary demand every day: charge when clean power is available, preserve comfort, and keep capacity observable.</Body><div style={{ marginTop: 30, fontFamily: 'var(--font-mono)', color: 'var(--color-secondary)', letterSpacing: '0.14em' }}>HOME SCALE · DAILY FLEXIBILITY</div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 14, marginTop: 12, maxWidth: 980 }}><div style={{ padding: 20, background: 'color-mix(in srgb, var(--color-washi-solar) 16%, transparent)', borderTop: '5px solid var(--color-washi-solar)' }}><strong>SOLAR NOON</strong><br />Clean power is abundant.</div><div style={{ padding: 20, background: 'color-mix(in srgb, var(--color-secondary) 13%, transparent)', borderTop: '5px solid var(--color-secondary)' }}><strong>FLEXIBLE LOAD</strong><br />EV, battery, and heat shift here.</div><div style={{ padding: 20, background: 'color-mix(in srgb, var(--color-washi-alert) 11%, transparent)', borderTop: '5px solid var(--color-washi-alert)' }}><strong>EVENING PEAK</strong><br />Comfort stays protected.</div></div></Slide>
    <Slide {...page}><Title>EVs can become controllable capacity</Title><div style={{ display: 'grid', gridTemplateColumns: '1fr 1.2fr', gap: 28, alignItems: 'center', marginTop: 26 }}><div style={{ padding: '28px 30px', background: 'color-mix(in srgb, var(--color-secondary) 13%, transparent)', borderLeft: '8px solid var(--color-secondary)' }}><div style={{ fontFamily: 'var(--font-mono)', color: 'var(--color-secondary)', letterSpacing: '0.12em' }}>V2H DEMONSTRATION · JAN 2024</div><div style={{ marginTop: 12, fontFamily: 'var(--font-heading)', fontSize: 66, lineHeight: 1 }}>186</div><div style={{ fontFamily: 'var(--font-mono)', letterSpacing: '0.12em' }}>HOUSEHOLD EVs</div></div><div><Body>Shizen Connect reported a demonstration coordinating household EVs through V2H systems.</Body><div style={{ display: 'flex', gap: 10, alignItems: 'center', fontFamily: 'var(--font-mono)', color: 'var(--color-secondary)' }}><span style={{ padding: '8px 12px', border: '1px solid currentColor' }}>EV</span><span>→</span><span style={{ padding: '8px 12px', border: '1px solid currentColor' }}>V2H</span><span>→</span><span style={{ padding: '8px 12px', border: '1px solid currentColor' }}>CONTROL</span></div></div></div><Source evidence={E.shizenV2H} caseNote={{ title: 'Shizen Connect · January 2024', scope: '186 household EVs controlled through V2H', qualifier: '90% control accuracy · company-reported' }} /></Slide>
    <Slide {...page}><Title>HEMS can coordinate the home</Title><div style={{ display: 'grid', gridTemplateColumns: '1.1fr .9fr', gap: 28, marginTop: 26 }}><div style={{ padding: 28, background: 'color-mix(in srgb, var(--color-primary) 9%, transparent)', border: '1px solid var(--color-primary)' }}><div style={{ fontFamily: 'var(--font-mono)', color: 'var(--color-primary)', letterSpacing: '0.12em' }}>DEMONSTRATION SCOPE</div><div style={{ marginTop: 20, display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 10, textAlign: 'center', fontFamily: 'var(--font-mono)' }}><span style={{ padding: 14, border: '1px solid var(--color-primary)' }}>HEMS</span><span style={{ padding: 14, border: '1px solid var(--color-primary)' }}>BATTERY</span><span style={{ padding: 14, border: '1px solid var(--color-primary)' }}>HOME</span></div></div><div><div style={{ fontFamily: 'var(--font-mono)', color: 'var(--color-secondary)', letterSpacing: '0.12em' }}>SIMULATED CAPACITY-MARKET DR</div><Body>Kansai Electric and Shizen Connect tested HEMS-controlled residential batteries in a technical-feasibility demonstration.</Body></div></div><Source evidence={E.kansaiHems} caseNote={{ title: 'Kansai Electric × Shizen Connect', scope: 'HEMS capacity-market technical-feasibility demonstration', qualifier: 'Demonstration scope · no commercial outcome claimed' }} /></Slide>
    <Slide {...page}><div style={{ fontFamily: 'var(--font-mono)', color: 'var(--color-secondary)', letterSpacing: '0.16em' }}>FLEET SCALE</div><Title>Aggregation makes a fleet legible</Title><Body>Individual devices become neighborhood, city, regional, and portfolio capacity without losing operational visibility.</Body><div style={{ height: 340 }}><Lazy><AggregationPyramid /></Lazy></div></Slide>
    <Slide padding="0"><div style={{ height: '100%', position: 'relative', background: 'var(--color-bg)' }}><Lazy><JapanVPPMap height={580} /></Lazy><div style={{ position: 'absolute', top: 26, left: 32 }}><div style={{ fontFamily: 'var(--font-mono)', color: 'var(--color-secondary)', letterSpacing: '0.16em' }}>JAPAN SCALE · COORDINATION MECHANICS</div><Title tone="var(--color-heading)">SIMULATED DISPATCH</Title><Body tone="var(--color-heading)">This visual demonstrates coordination mechanics; it is not a Shizen Connect outcome.</Body></div></div></Slide>
    <Slide {...darkPage}><div style={{ fontFamily: 'var(--font-mono)', color: 'var(--color-secondary)', letterSpacing: '0.16em' }}>ILLUSTRATIVE FLEET RESPONSE</div><Title tone="var(--color-heading)">Illustrative portfolio response</Title><Body tone="var(--color-heading)">Software can coordinate a distributed fleet as one operational resource. The capacity shown in the prior map is simulated.</Body><div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 16, marginTop: 34, maxWidth: 1040 }}><div style={{ padding: 24, borderTop: '5px solid var(--color-secondary)', background: 'color-mix(in srgb, var(--color-secondary) 13%, transparent)' }}><div style={{ fontFamily: 'var(--font-mono)', color: 'var(--color-secondary)' }}>01 · OBSERVED</div><div style={{ marginTop: 12, color: 'var(--color-heading)', fontSize: 30 }}>fleet state visible</div></div><div style={{ padding: 24, borderTop: '5px solid var(--color-primary)', background: 'color-mix(in srgb, var(--color-primary) 13%, transparent)' }}><div style={{ fontFamily: 'var(--font-mono)', color: 'var(--color-primary)' }}>02 · DISPATCHED</div><div style={{ marginTop: 12, color: 'var(--color-heading)', fontSize: 30 }}>intent sent safely</div></div><div style={{ padding: 24, borderTop: '5px solid var(--color-washi-solar)', background: 'color-mix(in srgb, var(--color-washi-solar) 13%, transparent)' }}><div style={{ fontFamily: 'var(--font-mono)', color: 'var(--color-washi-solar)' }}>03 · CONFIRMED</div><div style={{ marginTop: 12, color: 'var(--color-heading)', fontSize: 30 }}>dispatch acknowledged</div></div></div></Slide>

    <Slide {...page}><Title>What cloud-native teams can build</Title><Body>Event streams for telemetry. Actors for fleet state. GitOps for safe change. Traces that make every response explainable.</Body></Slide>
    <Slide {...page}><Title>Homes become a power plant when software earns trust</Title><Body>Not a fixed number of homes: a verifiable, observable, responsive portfolio that can grow as assets join.</Body></Slide>
    <Slide {...page}><Title>Keep exploring</Title><Body>whatisavpp.com/research/japan-energy-flexibility</Body><Body>Sources, case notes, and the technical appendix live there — while this talk remains self-contained.</Body></Slide>
    <Slide {...page}><div style={{ height: '100%', display: 'grid', placeItems: 'center', textAlign: 'center' }}><div><Title>Japan needs flexibility.</Title><Body>The grid is a distributed system. We know how to build those.</Body></div></div></Slide>
  </Deck></>;
}
