[build]
  command = "make netlify-build"
  publish = "presentation/dist"

[[redirects]]
  from = "/japan-keynote/*"
  to = "/japan-keynote/index.html"
  status = 200

[[redirects]]
  from = "/japan-main/*"
  to = "/japan-main/main-talk.html"
  status = 200

[[edge_functions]]
  path = "/*"
  function = "auth"
